/*
 * generated by Xtext 2.34.0
 */
package at.jku.isse.parser.antlr;

import at.jku.isse.parser.antlr.internal.InternalOCLXParser;
import at.jku.isse.services.OCLXGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class OCLXParser extends AbstractAntlrParser {

	@Inject
	private OCLXGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalOCLXParser createParser(XtextTokenStream stream) {
		return new InternalOCLXParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public OCLXGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(OCLXGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
