/**
 * generated by Xtext 2.34.0
 */
package at.jku.isse.oclx;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see at.jku.isse.oclx.OclxPackage#getBooleanOperator()
 * @model
 * @generated
 */
public interface BooleanOperator extends BinaryOperator
{
} // BooleanOperator
