/**
 * generated by Xtext 2.34.0
 */
package at.jku.isse.oclx;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.jku.isse.oclx.Constraint#getName <em>Name</em>}</li>
 *   <li>{@link at.jku.isse.oclx.Constraint#getDescription <em>Description</em>}</li>
 *   <li>{@link at.jku.isse.oclx.Constraint#isOverrulable <em>Overrulable</em>}</li>
 *   <li>{@link at.jku.isse.oclx.Constraint#getContext <em>Context</em>}</li>
 *   <li>{@link at.jku.isse.oclx.Constraint#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see at.jku.isse.oclx.OclxPackage#getConstraint()
 * @model
 * @generated
 */
public interface Constraint extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see at.jku.isse.oclx.OclxPackage#getConstraint_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link at.jku.isse.oclx.Constraint#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see at.jku.isse.oclx.OclxPackage#getConstraint_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link at.jku.isse.oclx.Constraint#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Overrulable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Overrulable</em>' attribute.
   * @see #setOverrulable(boolean)
   * @see at.jku.isse.oclx.OclxPackage#getConstraint_Overrulable()
   * @model
   * @generated
   */
  boolean isOverrulable();

  /**
   * Sets the value of the '{@link at.jku.isse.oclx.Constraint#isOverrulable <em>Overrulable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Overrulable</em>' attribute.
   * @see #isOverrulable()
   * @generated
   */
  void setOverrulable(boolean value);

  /**
   * Returns the value of the '<em><b>Context</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Context</em>' containment reference.
   * @see #setContext(Context)
   * @see at.jku.isse.oclx.OclxPackage#getConstraint_Context()
   * @model containment="true"
   * @generated
   */
  Context getContext();

  /**
   * Sets the value of the '{@link at.jku.isse.oclx.Constraint#getContext <em>Context</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Context</em>' containment reference.
   * @see #getContext()
   * @generated
   */
  void setContext(Context value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Exp)
   * @see at.jku.isse.oclx.OclxPackage#getConstraint_Expression()
   * @model containment="true"
   * @generated
   */
  Exp getExpression();

  /**
   * Sets the value of the '{@link at.jku.isse.oclx.Constraint#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Exp value);

} // Constraint
