/**
 * generated by Xtext 2.34.0
 */
package at.jku.isse.oclx;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Float Literal Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.jku.isse.oclx.FloatLiteralExp#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see at.jku.isse.oclx.OclxPackage#getFloatLiteralExp()
 * @model
 * @generated
 */
public interface FloatLiteralExp extends PrimitiveLiteralExp
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(float)
   * @see at.jku.isse.oclx.OclxPackage#getFloatLiteralExp_Value()
   * @model
   * @generated
   */
  float getValue();

  /**
   * Sets the value of the '{@link at.jku.isse.oclx.FloatLiteralExp#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(float value);

} // FloatLiteralExp
