/**
 * generated by Xtext 2.34.0
 */
package at.jku.isse.oclx;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Infix Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.jku.isse.oclx.InfixExp#getExpressions <em>Expressions</em>}</li>
 *   <li>{@link at.jku.isse.oclx.InfixExp#getOperators <em>Operators</em>}</li>
 * </ul>
 *
 * @see at.jku.isse.oclx.OclxPackage#getInfixExp()
 * @model
 * @generated
 */
public interface InfixExp extends Exp
{
  /**
   * Returns the value of the '<em><b>Expressions</b></em>' containment reference list.
   * The list contents are of type {@link at.jku.isse.oclx.Exp}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressions</em>' containment reference list.
   * @see at.jku.isse.oclx.OclxPackage#getInfixExp_Expressions()
   * @model containment="true"
   * @generated
   */
  EList<Exp> getExpressions();

  /**
   * Returns the value of the '<em><b>Operators</b></em>' containment reference list.
   * The list contents are of type {@link at.jku.isse.oclx.BinaryOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operators</em>' containment reference list.
   * @see at.jku.isse.oclx.OclxPackage#getInfixExp_Operators()
   * @model containment="true"
   * @generated
   */
  EList<BinaryOperator> getOperators();

} // InfixExp
