/**
 * generated by Xtext 2.34.0
 */
package at.jku.isse.oclx;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Iterator Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.jku.isse.oclx.IteratorExp#getName <em>Name</em>}</li>
 *   <li>{@link at.jku.isse.oclx.IteratorExp#getItervar <em>Itervar</em>}</li>
 *   <li>{@link at.jku.isse.oclx.IteratorExp#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see at.jku.isse.oclx.OclxPackage#getIteratorExp()
 * @model
 * @generated
 */
public interface IteratorExp extends MethodExp
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(IteratorName)
   * @see at.jku.isse.oclx.OclxPackage#getIteratorExp_Name()
   * @model containment="true"
   * @generated
   */
  IteratorName getName();

  /**
   * Sets the value of the '{@link at.jku.isse.oclx.IteratorExp#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(IteratorName value);

  /**
   * Returns the value of the '<em><b>Itervar</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Itervar</em>' containment reference.
   * @see #setItervar(IteratorVarDeclaration)
   * @see at.jku.isse.oclx.OclxPackage#getIteratorExp_Itervar()
   * @model containment="true"
   * @generated
   */
  IteratorVarDeclaration getItervar();

  /**
   * Sets the value of the '{@link at.jku.isse.oclx.IteratorExp#getItervar <em>Itervar</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Itervar</em>' containment reference.
   * @see #getItervar()
   * @generated
   */
  void setItervar(IteratorVarDeclaration value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(Exp)
   * @see at.jku.isse.oclx.OclxPackage#getIteratorExp_Body()
   * @model containment="true"
   * @generated
   */
  Exp getBody();

  /**
   * Sets the value of the '{@link at.jku.isse.oclx.IteratorExp#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(Exp value);

} // IteratorExp
