/**
 * generated by Xtext 2.34.0
 */
package at.jku.isse.oclx;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Method Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see at.jku.isse.oclx.OclxPackage#getMethodExp()
 * @model
 * @generated
 */
public interface MethodExp extends EObject
{
} // MethodExp
