/**
 * generated by Xtext 2.34.0
 */
package at.jku.isse.oclx;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Navigation Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.jku.isse.oclx.NavigationExp#getNav <em>Nav</em>}</li>
 *   <li>{@link at.jku.isse.oclx.NavigationExp#getMethods <em>Methods</em>}</li>
 * </ul>
 *
 * @see at.jku.isse.oclx.OclxPackage#getNavigationExp()
 * @model
 * @generated
 */
public interface NavigationExp extends Exp
{
  /**
   * Returns the value of the '<em><b>Nav</b></em>' containment reference list.
   * The list contents are of type {@link at.jku.isse.oclx.NavigationOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nav</em>' containment reference list.
   * @see at.jku.isse.oclx.OclxPackage#getNavigationExp_Nav()
   * @model containment="true"
   * @generated
   */
  EList<NavigationOperator> getNav();

  /**
   * Returns the value of the '<em><b>Methods</b></em>' containment reference list.
   * The list contents are of type {@link at.jku.isse.oclx.MethodExp}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Methods</em>' containment reference list.
   * @see at.jku.isse.oclx.OclxPackage#getNavigationExp_Methods()
   * @model containment="true"
   * @generated
   */
  EList<MethodExp> getMethods();

} // NavigationExp
