/**
 * generated by Xtext 2.34.0
 */
package at.jku.isse.oclx;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nested Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.jku.isse.oclx.NestedExp#getSource <em>Source</em>}</li>
 * </ul>
 *
 * @see at.jku.isse.oclx.OclxPackage#getNestedExp()
 * @model
 * @generated
 */
public interface NestedExp extends Exp
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' containment reference.
   * @see #setSource(Exp)
   * @see at.jku.isse.oclx.OclxPackage#getNestedExp_Source()
   * @model containment="true"
   * @generated
   */
  Exp getSource();

  /**
   * Sets the value of the '{@link at.jku.isse.oclx.NestedExp#getSource <em>Source</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' containment reference.
   * @see #getSource()
   * @generated
   */
  void setSource(Exp value);

} // NestedExp
