/**
 * generated by Xtext 2.34.0
 */
package at.jku.isse.oclx;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Null Literal Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see at.jku.isse.oclx.OclxPackage#getNullLiteralExpCS()
 * @model
 * @generated
 */
public interface NullLiteralExpCS extends NullLiteralExp
{
} // NullLiteralExpCS
