/**
 * generated by Xtext 2.34.0
 */
package at.jku.isse.oclx;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see at.jku.isse.oclx.OclxPackage
 * @generated
 */
public interface OclxFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  OclxFactory eINSTANCE = at.jku.isse.oclx.impl.OclxFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constraint</em>'.
   * @generated
   */
  Constraint createConstraint();

  /**
   * Returns a new object of class '<em>Context</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Context</em>'.
   * @generated
   */
  Context createContext();

  /**
   * Returns a new object of class '<em>Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exp</em>'.
   * @generated
   */
  Exp createExp();

  /**
   * Returns a new object of class '<em>Binary Operator</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Binary Operator</em>'.
   * @generated
   */
  BinaryOperator createBinaryOperator();

  /**
   * Returns a new object of class '<em>Boolean Operator</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Boolean Operator</em>'.
   * @generated
   */
  BooleanOperator createBooleanOperator();

  /**
   * Returns a new object of class '<em>Math Operator</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Math Operator</em>'.
   * @generated
   */
  MathOperator createMathOperator();

  /**
   * Returns a new object of class '<em>Navigation Operator</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Navigation Operator</em>'.
   * @generated
   */
  NavigationOperator createNavigationOperator();

  /**
   * Returns a new object of class '<em>Unary Operator</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Unary Operator</em>'.
   * @generated
   */
  UnaryOperator createUnaryOperator();

  /**
   * Returns a new object of class '<em>Nested Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Nested Exp</em>'.
   * @generated
   */
  NestedExp createNestedExp();

  /**
   * Returns a new object of class '<em>Self Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Self Exp</em>'.
   * @generated
   */
  SelfExp createSelfExp();

  /**
   * Returns a new object of class '<em>Var Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Var Declaration</em>'.
   * @generated
   */
  VarDeclaration createVarDeclaration();

  /**
   * Returns a new object of class '<em>Var Reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Var Reference</em>'.
   * @generated
   */
  VarReference createVarReference();

  /**
   * Returns a new object of class '<em>Primitive Literal Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Primitive Literal Exp</em>'.
   * @generated
   */
  PrimitiveLiteralExp createPrimitiveLiteralExp();

  /**
   * Returns a new object of class '<em>Int Literal Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Int Literal Exp</em>'.
   * @generated
   */
  IntLiteralExp createIntLiteralExp();

  /**
   * Returns a new object of class '<em>String Literal Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Literal Exp</em>'.
   * @generated
   */
  StringLiteralExp createStringLiteralExp();

  /**
   * Returns a new object of class '<em>Boolean Literal Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Boolean Literal Exp</em>'.
   * @generated
   */
  BooleanLiteralExp createBooleanLiteralExp();

  /**
   * Returns a new object of class '<em>Float Literal Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Float Literal Exp</em>'.
   * @generated
   */
  FloatLiteralExp createFloatLiteralExp();

  /**
   * Returns a new object of class '<em>Method Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Method Exp</em>'.
   * @generated
   */
  MethodExp createMethodExp();

  /**
   * Returns a new object of class '<em>Iterator Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Iterator Exp</em>'.
   * @generated
   */
  IteratorExp createIteratorExp();

  /**
   * Returns a new object of class '<em>Iterator Name</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Iterator Name</em>'.
   * @generated
   */
  IteratorName createIteratorName();

  /**
   * Returns a new object of class '<em>Iterator Var Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Iterator Var Declaration</em>'.
   * @generated
   */
  IteratorVarDeclaration createIteratorVarDeclaration();

  /**
   * Returns a new object of class '<em>Property Access Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Property Access Exp</em>'.
   * @generated
   */
  PropertyAccessExp createPropertyAccessExp();

  /**
   * Returns a new object of class '<em>Method Call Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Method Call Exp</em>'.
   * @generated
   */
  MethodCallExp createMethodCallExp();

  /**
   * Returns a new object of class '<em>Type Call Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type Call Exp</em>'.
   * @generated
   */
  TypeCallExp createTypeCallExp();

  /**
   * Returns a new object of class '<em>Type Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type Exp</em>'.
   * @generated
   */
  TypeExp createTypeExp();

  /**
   * Returns a new object of class '<em>Collection Type Identifier</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Collection Type Identifier</em>'.
   * @generated
   */
  CollectionTypeIdentifier createCollectionTypeIdentifier();

  /**
   * Returns a new object of class '<em>Temporal Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Temporal Exp</em>'.
   * @generated
   */
  TemporalExp createTemporalExp();

  /**
   * Returns a new object of class '<em>Unary Temporal Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Unary Temporal Exp</em>'.
   * @generated
   */
  UnaryTemporalExp createUnaryTemporalExp();

  /**
   * Returns a new object of class '<em>Triggered Temporal Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Triggered Temporal Exp</em>'.
   * @generated
   */
  TriggeredTemporalExp createTriggeredTemporalExp();

  /**
   * Returns a new object of class '<em>Arguments Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Arguments Exp</em>'.
   * @generated
   */
  ArgumentsExp createArgumentsExp();

  /**
   * Returns a new object of class '<em>Infix Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Infix Exp</em>'.
   * @generated
   */
  InfixExp createInfixExp();

  /**
   * Returns a new object of class '<em>Prefix Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Prefix Exp</em>'.
   * @generated
   */
  PrefixExp createPrefixExp();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  OclxPackage getOclxPackage();

} //OclxFactory
