/**
 * generated by Xtext 2.34.0
 */
package at.jku.isse.oclx;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Prefix Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.jku.isse.oclx.PrefixExp#getOperator <em>Operator</em>}</li>
 *   <li>{@link at.jku.isse.oclx.PrefixExp#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see at.jku.isse.oclx.OclxPackage#getPrefixExp()
 * @model
 * @generated
 */
public interface PrefixExp extends Exp
{
  /**
   * Returns the value of the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' containment reference.
   * @see #setOperator(UnaryOperator)
   * @see at.jku.isse.oclx.OclxPackage#getPrefixExp_Operator()
   * @model containment="true"
   * @generated
   */
  UnaryOperator getOperator();

  /**
   * Sets the value of the '{@link at.jku.isse.oclx.PrefixExp#getOperator <em>Operator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' containment reference.
   * @see #getOperator()
   * @generated
   */
  void setOperator(UnaryOperator value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Exp)
   * @see at.jku.isse.oclx.OclxPackage#getPrefixExp_Expression()
   * @model containment="true"
   * @generated
   */
  Exp getExpression();

  /**
   * Sets the value of the '{@link at.jku.isse.oclx.PrefixExp#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Exp value);

} // PrefixExp
