/**
 * generated by Xtext 2.34.0
 */
package at.jku.isse.oclx;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Prefix Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.jku.isse.oclx.PrefixExp#getOperators <em>Operators</em>}</li>
 *   <li>{@link at.jku.isse.oclx.PrefixExp#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see at.jku.isse.oclx.OclxPackage#getPrefixExp()
 * @model
 * @generated
 */
public interface PrefixExp extends Exp
{
  /**
   * Returns the value of the '<em><b>Operators</b></em>' containment reference list.
   * The list contents are of type {@link at.jku.isse.oclx.UnaryOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operators</em>' containment reference list.
   * @see at.jku.isse.oclx.OclxPackage#getPrefixExp_Operators()
   * @model containment="true"
   * @generated
   */
  EList<UnaryOperator> getOperators();

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Exp)
   * @see at.jku.isse.oclx.OclxPackage#getPrefixExp_Expression()
   * @model containment="true"
   * @generated
   */
  Exp getExpression();

  /**
   * Sets the value of the '{@link at.jku.isse.oclx.PrefixExp#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Exp value);

} // PrefixExp
