/**
 * generated by Xtext 2.34.0
 */
package at.jku.isse.oclx;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Triggered Temporal Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.jku.isse.oclx.TriggeredTemporalExp#getB <em>B</em>}</li>
 *   <li>{@link at.jku.isse.oclx.TriggeredTemporalExp#getA <em>A</em>}</li>
 * </ul>
 *
 * @see at.jku.isse.oclx.OclxPackage#getTriggeredTemporalExp()
 * @model
 * @generated
 */
public interface TriggeredTemporalExp extends TemporalExp
{
  /**
   * Returns the value of the '<em><b>B</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>B</em>' containment reference.
   * @see #setB(Exp)
   * @see at.jku.isse.oclx.OclxPackage#getTriggeredTemporalExp_B()
   * @model containment="true"
   * @generated
   */
  Exp getB();

  /**
   * Sets the value of the '{@link at.jku.isse.oclx.TriggeredTemporalExp#getB <em>B</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>B</em>' containment reference.
   * @see #getB()
   * @generated
   */
  void setB(Exp value);

  /**
   * Returns the value of the '<em><b>A</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>A</em>' containment reference.
   * @see #setA(Exp)
   * @see at.jku.isse.oclx.OclxPackage#getTriggeredTemporalExp_A()
   * @model containment="true"
   * @generated
   */
  Exp getA();

  /**
   * Sets the value of the '{@link at.jku.isse.oclx.TriggeredTemporalExp#getA <em>A</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>A</em>' containment reference.
   * @see #getA()
   * @generated
   */
  void setA(Exp value);

} // TriggeredTemporalExp
