/**
 * generated by Xtext 2.34.0
 */
package at.jku.isse.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.testing.validation.ValidationTestHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)/* 
@InjectWith(_OCLXInjectorProvider) */
@SuppressWarnings("all")
public class OCLXParsingTest {
  @Inject
  private /* ParseHelper<Model> */Object parseHelper;

  @Inject
  private ValidationTestHelper validationTestHelper;

  @Test
  public void loadAtomicContextFail() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field OclxPackage is undefined"
      + "\nThe field OCLXParsingTest.parseHelper refers to the missing type Model"
      + "\nLiterals cannot be resolved"
      + "\nCONSTRAINT cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }

  @Test
  public void loadKnownContext() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field OCLXParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }

  @Test
  public void loadUnknownContext() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field OclxPackage is undefined"
      + "\nThe field OCLXParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nCONSTRAINT cannot be resolved");
  }

  @Test
  public void loadSyntacticCorrectSmallModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field OCLXParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }

  @Test
  public void loadDuplicateVarDeclaration() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field OclxPackage is undefined"
      + "\nThe field OCLXParsingTest.parseHelper refers to the missing type Model"
      + "\nLiterals cannot be resolved"
      + "\nITERATOR_VAR_DECLARATION cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }

  @Test
  public void loadDuplicateVarDeclaration2() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field OclxPackage is undefined"
      + "\nThe field OCLXParsingTest.parseHelper refers to the missing type Model"
      + "\nLiterals cannot be resolved"
      + "\nITERATOR_VAR_DECLARATION cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }

  @Test
  public void loadKnownPropertyUsage() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field OCLXParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }

  @Test
  public void testFindUnknownTypeDeclaration() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field OclxPackage is undefined"
      + "\nThe field OCLXParsingTest.parseHelper refers to the missing type Model"
      + "\nLiterals cannot be resolved"
      + "\nTYPE_EXP cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }

  @Test
  public void testFindKnownTypeDeclaration() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field OCLXParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }

  @Test
  public void testUpcastVariable() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field OCLXParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }

  @Test
  public void testDowncastVariable() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field OclxPackage is undefined"
      + "\nThe field OCLXParsingTest.parseHelper refers to the missing type Model"
      + "\nLiterals cannot be resolved"
      + "\nPROPERTY_ACCESS_EXP cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }

  @Test
  public void testTemporalNestedReturnType() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field OclxPackage is undefined"
      + "\nThe field OCLXParsingTest.parseHelper refers to the missing type Model"
      + "\nLiterals cannot be resolved"
      + "\nEXP cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }

  @Test
  public void testTriggeredTemporalNestedReturnType() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field OclxPackage is undefined"
      + "\nThe field OCLXParsingTest.parseHelper refers to the missing type Model"
      + "\nLiterals cannot be resolved"
      + "\nEXP cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }

  @Test
  public void testTriggeredTemporalNestedReturnTypeSuccess() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field OCLXParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }

  @Test
  public void testCommentInlineSuccess() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field OCLXParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
