/*
 * generated by Xtext 2.34.0
 */
package at.jku.isse.ide;

import org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider;
import org.eclipse.xtext.ide.server.codeActions.ICodeActionService2;
import org.eclipse.xtext.ide.server.hover.HoverService;

import at.jku.isse.ide.contentproposal.OclxContentProposalProvider;
import at.jku.isse.ide.contentproposal.QuickFixCodeActionService;
import at.jku.isse.ide.contentproposal.TypeExtractor;
import at.jku.isse.ide.contentproposal.TypeHoverService;

/**
 * Use this class to register ide components.
 */
public class OCLXIdeModule extends AbstractOCLXIdeModule {
	
	
	// add quickfix service
	public Class<? extends ICodeActionService2> bindCodeActionService2() {
		return QuickFixCodeActionService.class;
	}
	
	
	public Class<? extends IdeContentProposalProvider> bindIdeContentProposalProvider() {
		return OclxContentProposalProvider.class;
	}
	
	public Class<TypeExtractor> bindTypeExtractor() {
		return TypeExtractor.class;
	}
	
	public Class<? extends HoverService> bindHoverService() {
		return TypeHoverService.class;
	}
	
}
